apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: rmtp
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30090
  selector:
    k8s-app: rmtp-lb

